---
- hosts: all
  roles:
    - kewlfft.aur
  tasks:
    - name: Install packages from the official repo
      community.general.pacman:
        update_cache: true
        name:
          - ansible
          - vagrant
          - terraform
          - virtualbox
          - virtualbox-host-modules-arch
          - zsh
          - lazygit
          - rust
          - man
          - tmux
          - fzf
          - fwupd
          - ansible-lint
          - yamllint
          - shellcheck
        state: present

    - name: Install AUR helper paru
      become_user: danesh
      aur:
        use: makepkg
        name:
          - paru
        state: present

#    - name: Install packages from the AUR
#      become_user: danesh
#      aur:
#        aur_only: true
#        use: paru
#        name:
#          - visual-studio-code-bin
#          - google-chrome-beta
#          - slack-desktop
#          - spotify
#          - teams
#          - ttf-meslo-nerd-font-powerlevel10k
#          - notion-app
#        state: present

    - name: Change default shell to zsh
      ansible.builtin.user:
        name: danesh
        shell: /usr/bin/zsh

    - name: Enable TRIM systemd unit
      ansible.builtin.systemd:
        name: fstrim.timer
        enabled: yes
        state: started
